- name: create LUKS container
  become: yes
  luks_device:
    device: "/dev/{{vg_name}}/{{lv_name}}"
    state: "present"
    keyfile: "/vault/keyfile"
## Breaks on 2nd run!
#     name: "{{vg_name}}-{{lv_name}}"
