# - import_tasks: luks.yml

- name: Remove the logical volume.
  become: yes
  lvol:
    vg: "{{vg_name}}"
    lv: "{{lv_name}}"
    state: absent
    force: yes

- name: Remove a volume group with name vg.services
  become: yes
  lvg:
    vg: "{{vg_name}}"
    state: absent
    force: yes
